name: zodgame

on:
  schedule:
  - cron: "0 0 * * *"
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install requirements
      run: pip install -r zodgame/requirements.txt
    - name: Run
      run: python zodgame/zodgame.py "$env:ZODGAME_COOKIE"
      env:
        ZODGAME_COOKIE: ${{ secrets.ZODGAME_COOKIE }}